name: e_commerce
description: "A Multiplaform app in flutter for e-commerce"
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.5
  go_router: ^14.1.4
  get_it: ^7.7.0
  uuid: ^4.4.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_progress_hud: ^2.0.2
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  loading_animation_widget: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1
  fpdart: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.6
  pocketbase: ^0.18.1
  equatable: ^2.0.5
  path_provider: ^2.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  toastification: ^2.0.0
  http: ^1.2.1
  flutter_stripe: ^11.0.0
  dio: ^5.5.0+1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
     - assets/svg/
     - .env


  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaWorld-Regular.ttf
        - asset: assets/fonts/HelveticaWorld-Bold.ttf
          weight: 700
        - asset: assets/fonts/HelveticaWorld-Italic.ttf
          style: italic
        - asset: assets/fonts/HelveticaWorld-BoldItalic.ttf
          weight: 700
          style: italic
